"""
Prometheus 監控指標模組
集中管理所有應用程式效能指標
"""

from prometheus_client import (
    Counter, Histogram, Gauge, CollectorRegistry
)

# === Prometheus 監控指標初始化 ===
# 創建 Prometheus 指標收集器，用於監控 AI Agent 效能
REGISTRY = CollectorRegistry()

# 延遲指標 (Latency)
alert_processing_duration = Histogram(
    'alert_processing_duration_seconds',
    'Time spent processing a single alert',
    registry=REGISTRY
)

api_call_duration = Histogram(
    'api_call_duration_seconds',
    'Time spent on API calls by stage',
    ['stage'],
    registry=REGISTRY
)

retrieval_duration = Histogram(
    'retrieval_duration_seconds',
    'Time spent on data retrieval',
    registry=REGISTRY
)

# Token 指標 (Token Usage)
llm_input_tokens_total = Counter(
    'llm_input_tokens_total',
    'Total input tokens used by LLM analysis',
    registry=REGISTRY
)

llm_output_tokens_total = Counter(
    'llm_output_tokens_total',
    'Total output tokens generated by LLM analysis',
    registry=REGISTRY
)

embedding_input_tokens_total = Counter(
    'embedding_input_tokens_total',
    'Total input tokens used by embedding service',
    registry=REGISTRY
)

# 吞吐量與隊列 (Throughput & Queue)
alerts_processed_total = Counter(
    'alerts_processed_total',
    'Total number of alerts successfully processed',
    registry=REGISTRY
)

new_alerts_found_total = Counter(
    'new_alerts_found_total',
    'Total number of new alerts found during polling',
    registry=REGISTRY
)

pending_alerts_gauge = Gauge(
    'pending_alerts_gauge',
    'Current number of pending alerts',
    registry=REGISTRY
)

# 錯誤率 (Error Rate)
alert_processing_errors_total = Counter(
    'alert_processing_errors_total',
    'Total number of alert processing failures',
    registry=REGISTRY
)

api_errors_total = Counter(
    'api_errors_total',
    'Total number of API call failures by stage',
    ['stage'],
    registry=REGISTRY
)

# GraphRAG 相關指標 - 改進版本
graph_retrieval_attempts_total = Counter(
    'graph_retrieval_attempts_total',
    'Total number of graph retrieval attempts',
    registry=REGISTRY
)

graph_retrieval_fallback_total = Counter(
    'graph_retrieval_fallback_total',
    'Total number of fallbacks from graph to traditional retrieval',
    registry=REGISTRY
)

graph_retrieval_success_total = Counter(
    'graph_retrieval_success_total',
    'Total number of successful graph retrievals',
    registry=REGISTRY
)

# 計算降級率的輔助指標
graph_retrieval_fallback_rate = Gauge(
    'graph_retrieval_fallback_rate',
    'Current fallback rate for graph retrieval (fallbacks/attempts)',
    registry=REGISTRY
)

# Graph 相關指標
graph_entities_created_total = Counter(
    'graph_entities_created_total',
    'Total number of graph entities created',
    ['entity_type'],
    registry=REGISTRY
)

graph_relationships_created_total = Counter(
    'graph_relationships_created_total',
    'Total number of graph relationships created',
    ['relationship_type'],
    registry=REGISTRY
)

graph_queries_executed_total = Counter(
    'graph_queries_executed_total',
    'Total number of graph queries executed',
    registry=REGISTRY
)

# 查詢效能指標
graph_query_duration = Histogram(
    'graph_query_duration_seconds',
    'Time spent executing graph queries',
    buckets=[0.01, 0.05, 0.1, 0.5, 1.0, 2.5, 5.0, 10.0],
    registry=REGISTRY
)

# 工具函數
def record_processing_time(duration: float):
    """記錄警報處理時間"""
    alert_processing_duration.observe(duration)

def record_api_call_time(stage: str, duration: float):
    """記錄 API 調用時間"""
    api_call_duration.labels(stage=stage).observe(duration)

def increment_alerts_processed():
    """增加已處理警報計數"""
    alerts_processed_total.inc()

def increment_processing_errors():
    """增加處理錯誤計數"""
    alert_processing_errors_total.inc()

def update_pending_alerts(count: int):
    """更新待處理警報數量"""
    pending_alerts_gauge.set(count)

# GraphRAG 相關工具函數
def record_graph_retrieval_attempt():
    """記錄圖形檢索嘗試"""
    graph_retrieval_attempts_total.inc()
    _update_fallback_rate()

def record_graph_retrieval_fallback():
    """記錄圖形檢索降級"""
    graph_retrieval_fallback_total.inc()
    _update_fallback_rate()

def record_graph_retrieval_success():
    """記錄圖形檢索成功"""
    graph_retrieval_success_total.inc()

def record_graph_query_time(duration: float):
    """記錄圖形查詢執行時間"""
    graph_query_duration.observe(duration)

def _update_fallback_rate():
    """更新降級率指標"""
    try:
        attempts = graph_retrieval_attempts_total._value.get()
        fallbacks = graph_retrieval_fallback_total._value.get()
        
        if attempts > 0:
            rate = fallbacks / attempts
            graph_retrieval_fallback_rate.set(rate)
        else:
            graph_retrieval_fallback_rate.set(0)
    except Exception:
        # 避免計算錯誤影響主流程
        pass

# 批量操作工具函數
def get_metrics_summary() -> dict:
    """獲取關鍵指標摘要"""
    try:
        attempts = graph_retrieval_attempts_total._value.get()
        fallbacks = graph_retrieval_fallback_total._value.get()
        successes = graph_retrieval_success_total._value.get()
        
        return {
            "alerts_processed": alerts_processed_total._value.get(),
            "processing_errors": alert_processing_errors_total._value.get(),
            "graph_retrieval": {
                "attempts": attempts,
                "successes": successes,
                "fallbacks": fallbacks,
                "fallback_rate": (fallbacks / attempts) if attempts > 0 else 0,
                "success_rate": (successes / attempts) if attempts > 0 else 0
            }
        }
    except Exception as e:
        logger.error(f"Error getting metrics summary: {e}")
        return {}

# 導入日誌模組（如果需要）
import logging
logger = logging.getLogger(__name__)